server:
  port: 4567
  servlet:
    context-path: /unity

mybatis-plus:
  type-aliases-package: com.jc.unity.model
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.133.53:3306/demo_build?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    username: root
    password: jiacheng
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  data:
    mongodb:
      host: 47.102.133.53
      port: 27017
      authentication-database: build_game
      database: build_game
      username: zjcBuildGame
      password: buildGame
      bucket-collect-num: 5
      #单位为字节,缺省大于1M存入bucket 1048576
      max-collect-file-size: 1048576
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB